// =============================================================================
// raytracer_top.v  —  Top-Level Wrapper
//
// Ties together:
//   ray_marcher  →  bram_manager  →  vga_display
//
// Clocking:
//   clk_in       : Ray-march clock (100 MHz from board)
//   vga_clk_in   : VGA pixel clock  (40 MHz for 800x600 @ 60 Hz)
//                  Generated by the Xilinx Clock Wizard IP (CLK_CONVERTER_TYPE).
//
// bram_manager swap strategy:
//   The BRAM is swapped at each new_frame_out pulse from ray_marcher.
//   This means vga_display always reads the last fully-rendered frame while
//   ray_marcher writes the next one into the shadow buffer.
// =============================================================================

`timescale 1ns / 1ps
`default_nettype none
`include "types.vh"

module raytracer_top (
    // Board clocks
    input  wire        clk_in,           // 100 MHz system clock
    input  wire        vga_clk_in,       // 40 MHz VGA pixel clock (from Clock Wizard IP)

    // Reset (active-high)
    input  wire        rst_in,

    // Camera inputs (from UART / buttons / keyboard controller)
    input  wire [3*`W-1:0] pos_vec_in,       // camera world position
    input  wire [3*`W-1:0] dir_vec_in,       // camera forward direction
    input  wire [2:0]      fractal_sel_in,   // which SDF scene

    // Render toggles
    input  wire        toggle_checker_in,
    input  wire        toggle_dither_in,
    input  wire        toggle_texture_in,

    // VGA toggles
    input  wire        toggle_hue_in,
    input  wire        toggle_color_in,

    // VGA output
    output wire [3:0]  vga_r,
    output wire [3:0]  vga_g,
    output wire [3:0]  vga_b,
    output wire        vga_hs,
    output wire        vga_vs
);

    // -------------------------------------------------------------------------
    // Local parameters
    // -------------------------------------------------------------------------
    localparam H_BITS    = `H_BITS;
    localparam V_BITS    = `V_BITS;
    localparam ADDR_BITS = `ADDR_BITS;          // H_BITS + V_BITS
    localparam BRAM_DEPTH = `DISPLAY_WIDTH * `DISPLAY_HEIGHT;

    // -------------------------------------------------------------------------
    // ray_marcher outputs
    // -------------------------------------------------------------------------
    wire [H_BITS-1:0] rm_hcount;
    wire [V_BITS-1:0] rm_vcount;
    wire [3:0]        rm_color;
    wire              rm_valid;
    wire              rm_new_frame;

    ray_marcher #(
        .DISPLAY_WIDTH (`DISPLAY_WIDTH),
        .DISPLAY_HEIGHT(`DISPLAY_HEIGHT),
        .H_BITS        (H_BITS),
        .V_BITS        (V_BITS),
        .COLOR_BITS    (4),
        .NUM_CORES     (`NUM_CORES)
    ) u_ray_marcher (
        .clk_in            (clk_in),
        .rst_in            (rst_in),
        .pos_vec_in        (pos_vec_in),
        .dir_vec_in        (dir_vec_in),
        .fractal_sel_in    (fractal_sel_in),
        .toggle_checker_in (toggle_checker_in),
        .toggle_dither_in  (toggle_dither_in),
        .toggle_texture_in (toggle_texture_in),
        .hcount_out        (rm_hcount),
        .vcount_out        (rm_vcount),
        .color_out         (rm_color),
        .valid_out         (rm_valid),
        .new_frame_out     (rm_new_frame)
    );

    // -------------------------------------------------------------------------
    // Write address: flatten (hcount, vcount) → linear pixel address
    // -------------------------------------------------------------------------
    wire [ADDR_BITS-1:0] write_addr;
    assign write_addr = (rm_vcount * `DISPLAY_WIDTH) + rm_hcount;

    // -------------------------------------------------------------------------
    // bram_manager — double-buffered pixel store
    // -------------------------------------------------------------------------
    wire [3:0]        bram_read_data;
    wire              bram_which;
    wire [ADDR_BITS-1:0] vga_read_addr;

    bram_manager #(
        .WIDTH   (4),
        .DEPTH   (BRAM_DEPTH),
        .ADDR_LEN(ADDR_BITS)
    ) u_bram (
        .clk           (clk_in),
        .rst           (rst_in),
        .swap_buffers  (rm_new_frame),    // swap on every completed frame
        .which_bram_out(bram_which),
        .write_addr    (write_addr),
        .write_data    (rm_color),
        .write_enable  (rm_valid),
        .read_addr     (vga_read_addr),
        .read_data_out (bram_read_data)
    );

    // -------------------------------------------------------------------------
    // vga_display — reads BRAM and drives VGA signals
    // -------------------------------------------------------------------------
    wire [3:0] vga_r_w, vga_g_w, vga_b_w;
    wire       vga_hs_w, vga_vs_w;

    vga_display u_vga (
        .vga_clk_in   (vga_clk_in),
        .rst_in       (rst_in),
        .read_data_in (bram_read_data),
        .toggle_hue   (toggle_hue_in),
        .toggle_color (toggle_color_in),
        .read_addr_out(vga_read_addr),
        .vga_r        (vga_r_w),
        .vga_g        (vga_g_w),
        .vga_b        (vga_b_w),
        .vga_hs       (vga_hs_w),
        .vga_vs       (vga_vs_w)
    );

    assign vga_r  = vga_r_w;
    assign vga_g  = vga_g_w;
    assign vga_b  = vga_b_w;
    assign vga_hs = vga_hs_w;
    assign vga_vs = vga_vs_w;

endmodule

`default_nettype wire
